apiVersion: v1
kind: Service
metadata:
  name: recommender-service
spec:
  type: LoadBalancer # <-- Allows external traffic access (key resume point)
  ports:
    - port: 80 # Public port (standard HTTP)
      targetPort: 8501 # Internal container port
      protocol: TCP
  selector:
    app: recommender # Connects traffic to the 'recommender-deployment' pods
