# .streamlit/config.toml

[server]
# This setting is necessary to allow the app to be viewed on the web
headless = true

[theme]
# You can customize your app's theme here for extra polish
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[global]
# This disables the welcome page and ensures the app loads directly
showWarningOnDirectExecution = false